[tool.poetry]
name = "cleo"
version = "0.7.6+typefix1"
description = "Cleo allows you to create beautiful and testable command-line interfaces."
authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]
license = "MIT"

readme = "README.rst"

homepage = "https://github.com/sdispater/cleo"

keywords = ["cli", "commands"]

# Requirements
[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
clikit = "^0.4.0"


[tool.poetry.dev-dependencies]
pytest = "^4.4"
pytest-mock = "^1.7"
pre-commit = "^1.12"
pytest-cov = "^2.6"
tox = "^3.5"
black = {version = "^19.3b0", python = "^3.6"}


[build-system]
requires = ["poetry>=1.0.0b2"]
build-backend = "poetry.masonry.api"
